services:
  m241.server:
    image: jzeladminbbzw2006/aircheck-backend
    environment:
      - FrontendUrl=https://rpi.m241.api64.de
  m241.frontend:
    image: jzeladminbbzw2006/aircheck-frontend
    ports:
      - 3000:80
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.secure.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live/m241.api64.de/fullchain.pem:/etc/ssl/rpi.pem:ro
      - /etc/letsencrypt/live/m241.api64.de/privkey.pem:/etc/ssl/private/rpi.pem:ro
    depends_on:
      - m241.server
      - m241.frontend
