services:
  m241.server:
    image: ${DOCKER_REGISTRY-}m241server
    build:
      context: .
      dockerfile: M241.Server/Dockerfile
    environment:
        - ConnectionStrings__Default=Host=postgres;Port=5432;Database=m241;Username=dbuser;Password=admin;
        - ASPNETCORE_ENVIRONMENT=Release
        - ASPNETCORE_HTTP_PORTS=80
        - MQTT__server=mosquitto;
        - MQTT__user=mosquitto;
        - MQTT__password=admin;
    ports:
      - "80:80"
    depends_on:
        - mosquitto
  mosquitto:
    build: ./M241.Broker
    environment:
      - MOSQUITTO_USERNAME=${MOSQUITTO_USERNAME:-mosquitto}
      - MOSQUITTO_PASSWORD=${MOSQUITTO_PASSWORD:-admin}
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    ports:
      - 1883:1883
      - 9002:9001
volumes:
  m241_db:
  mosquitto_data:
  mosquitto_log:
