services:
  m241.server:
    image: ${DOCKER_REGISTRY-}m241server
    build:
      context: .
      dockerfile: M241.Server/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    ports:
      - "8086:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres
