services:
  m241.server:
    image: jzeladminbbzw2006/aircheck-backend
    environment:
      - FrontendUrl=https://aircheck.jzel.ch
  m241.frontend:
    image: jzeladminbbzw2006/aircheck-frontend
    ports:
      - 3000:80
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.secure.conf:/etc/nginx/nginx.conf:ro
      - /home/pi/m241/Letsencrypt/certs/fullchain.pem:/etc/ssl/rpi.pem:ro
      - /home/pi/m241/Letsencrypt/certs/privkey.pem:/etc/ssl/private/rpi.pem:ro
    depends_on:
      - m241.server
      - m241.frontend