services:
  m241.server:
    image: ${CONTAINERREGISTRY}/aircheck-backend
    environment:
      - FrontendUrl=https://${URL}
  m241.frontend:
    image: ${CONTAINERREGISTRY}/aircheck-frontend
    ports:
      - 3000:80
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.secure.conf:/etc/nginx/nginx.conf:ro
      - ${CERTPATH}/fullchain.pem:/etc/ssl/rpi.pem:ro
      - ${CERTPATH}/privkey.pem:/etc/ssl/private/rpi.pem:ro
    depends_on:
      - m241.server
      - m241.frontend