services:
  m241.server:
    image: jzeladminbbzw2006/aircheck-backend
    environment:
      - ConnectionStrings__Default=Host=postgres;Port=5432;Database=m241;Username=dbuser;Password=admin;
      - ASPNETCORE_ENVIRONMENT=Release
      - ASPNETCORE_HTTP_PORTS=80
      - MQTT__server=mosquitto
      - MQTT__user=mosquitto
      - MQTT__password=admin
    ports:
      - "8081:80"
    depends_on:
      - mosquitto
      - postgres
  m241.frontend:
    image: jzeladminbbzw2006/aircheck-frontend
    ports:
      - 3000:80
  mosquitto:
    build: ./M241.Broker
    environment:
      - MOSQUITTO_USERNAME=${MOSQUITTO_USERNAME:-mosquitto}
      - MOSQUITTO_PASSWORD=${MOSQUITTO_PASSWORD:-admin}
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    ports:
      - 1883:1883
      - 9002:9001
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - m241_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=dbuser
      - POSTGRES_DB=m241
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - m241.server
      - m241.frontend
volumes:
  m241_db:
  mosquitto_data:
  mosquitto_log:
  pgadmin_data:
