services:
  m241.server:
    image: jzeladminbbzw2006/aircheck-backend
    environment:
      - ConnectionStrings__Default=Host=postgres;Port=5432;Database=m241;Username=dbuser;Password=admin;
      - ASPNETCORE_ENVIRONMENT=Release
      - ASPNETCORE_HTTP_PORTS=80
      - MQTT__server=mosquitto
      - MQTT__user=mosquitto
      - MQTT__password=admin
    ports:
      - "8081:80"
    depends_on:
      - mosquitto
      - postgres
    restart: always
  mosquitto:
    build: 
     context: .
     dockerfile: ./M241.Broker/Dockerfile
     args:
        CERTPATH: ${CERTPATH}
    environment:
      - MOSQUITTO_USERNAME=${MOSQUITTO_USERNAME:-mosquitto}
      - MOSQUITTO_PASSWORD=${MOSQUITTO_PASSWORD:-admin}
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    ports:
      - 8883:8883
      - 9002:9001
    restart: always
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - m241_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=dbuser
      - POSTGRES_DB=m241
    restart: always

volumes:
  m241_db:
  mosquitto_data:
  mosquitto_log:
  pgadmin_data:
